# Generated by Django 5.2.4 on 2025-07-25 17:31

import django.db.models.deletion
import koguilator.validate_pass
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_usuario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('email', models.CharField(max_length=255, unique=True, verbose_name='Email')),
                ('senha', models.CharField(max_length=128, validators=[koguilator.validate_pass.validar_senha], verbose_name='Senha')),
                ('data_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Inclusão')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id_operacao', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parametros', models.CharField(max_length=255, verbose_name='Parâmetros')),
                ('resultado', models.CharField(max_length=255, verbose_name='Resultado')),
                ('data_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Inclusão')),
                ('idUsuario', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='operacoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
    ]
